### ISSUE TITLE
A question about preocess ace05e

### ISSUE THREAD

**Issue by Alienboyplus** [PlusLabNLP/AMPERE#4]
Hi, I am intersted in your work!

I followed the instructions of [dygiepp](https://github.com/dwadden/dygiepp?tab=readme-ov-file#creating-the-dataset-1) and got `train.json`, `test.json`, `dev.json`.

When I `bash  ./scripts/process_ace05e.sh ` , it shows:
```
Traceback (most recent call last):
  File "preprocessing/process_ace05e.py", line 202, in <module>
    convert(args.input, args.output, bert_tokenizer, args.window)
  File "preprocessing/process_ace05e.py", line 41, in convert
    coref_entities = doc['clusters']
KeyError: 'clusters'
Traceback (most recent call last):
  File "preprocessing/process_ace05e.py", line 202, in <module>
    convert(args.input, args.output, bert_tokenizer, args.window)
  File "preprocessing/process_ace05e.py", line 41, in convert
    coref_entities = doc['clusters']
KeyError: 'clusters'
Traceback (most recent call last):
  File "preprocessing/process_ace05e.py", line 202, in <module>
    convert(args.input, args.output, bert_tokenizer, args.window)
  File "preprocessing/process_ace05e.py", line 41, in convert
    coref_entities = doc['clusters']
KeyError: 'clusters'
```

This is my dataset structure, but the **clusters'** and **event_clusters** are missing. 

![image](https://github.com/PlusLabNLP/AMPERE/assets/38063098/35433732-308e-40ca-832b-b2be4b666052)

**Can you provide the environment list and processing steps(i.e. bash commans) used in dygiepp ?**
Many thanks !!!

**Comment by Alienboyplus** [comment]
sorry :( 

I forgot to add `--include_entity_coreference` and `--include_event_coreference`

it works now XD
